import type { CompetitionDivision, CompetitionKind } from "@/lib/types";

export interface CompetitionSeedEntry {
  slug: string;
  title: string;
  kind: CompetitionKind;
  sportName: string;
  division: CompetitionDivision;
  formatLabel?: string;
  registrationFee: number;
  winnerPrize?: number;
  runnerUpPrize?: number;
  secondRunnerUpPrize?: number;
  displayOrder: number;
}

export interface SportSeedEntry {
  name: string;
  accent: string;
  tagline: string;
}

export const sportSeedEntries: SportSeedEntry[] = [
  {
    name: "Volleyball",
    accent: "#df4f3e",
    tagline: "Big blocks, long rallies, and loud final points.",
  },
  {
    name: "Basketball",
    accent: "#1ca79a",
    tagline: "Sharp drives, quick switches, and full-court pressure.",
  },
  {
    name: "Kabaddi",
    accent: "#ebb04a",
    tagline: "One breath, one raid, and a swing in momentum.",
  },
  {
    name: "Football",
    accent: "#3d8cdb",
    tagline: "Fast breaks, packed boxes, and late-match drama.",
  },
  {
    name: "Badminton",
    accent: "#f08c3c",
    tagline: "Quick feet, clean timing, and sharp-angle winners.",
  },
  {
    name: "Table Tennis",
    accent: "#6f7bf7",
    tagline: "Compact reactions, rapid rallies, and precise placement.",
  },
  {
    name: "Chess",
    accent: "#5f6b76",
    tagline: "Quiet pressure, long calculation, and one decisive sequence.",
  },
  {
    name: "BGMI",
    accent: "#6f4bf2",
    tagline: "Squad survival, rotations, and end-zone composure.",
  },
  {
    name: "Free Fire",
    accent: "#e65b2d",
    tagline: "Aggressive drops, quick looting, and close-circle fights.",
  },
  {
    name: "Real Cricket",
    accent: "#2ca06b",
    tagline: "Pocket cricket with quick innings and clean shot selection.",
  },
  {
    name: "Valorant",
    accent: "#ff4655",
    tagline: "Tactical rounds, utility timing, and clutch finishes.",
  },
];

export const competitionSeedEntries: CompetitionSeedEntry[] = [
  {
    slug: "volleyball-men",
    title: "Volleyball",
    kind: "SPORT",
    sportName: "Volleyball",
    division: "MEN",
    registrationFee: 3500,
    winnerPrize: 30000,
    runnerUpPrize: 20000,
    displayOrder: 1,
  },
  {
    slug: "basketball-men",
    title: "Basketball",
    kind: "SPORT",
    sportName: "Basketball",
    division: "MEN",
    registrationFee: 3500,
    winnerPrize: 25000,
    runnerUpPrize: 15000,
    displayOrder: 2,
  },
  {
    slug: "kabaddi-men",
    title: "Kabaddi",
    kind: "SPORT",
    sportName: "Kabaddi",
    division: "MEN",
    registrationFee: 3500,
    winnerPrize: 30000,
    runnerUpPrize: 20000,
    displayOrder: 3,
  },
  {
    slug: "football-men",
    title: "Football",
    kind: "SPORT",
    sportName: "Football",
    division: "MEN",
    registrationFee: 3000,
    winnerPrize: 25000,
    runnerUpPrize: 15000,
    displayOrder: 4,
  },
  {
    slug: "badminton-singles-men",
    title: "Badminton Singles",
    kind: "SPORT",
    sportName: "Badminton",
    division: "MEN",
    formatLabel: "Singles",
    registrationFee: 250,
    winnerPrize: 5000,
    runnerUpPrize: 3000,
    displayOrder: 5,
  },
  {
    slug: "badminton-doubles-men",
    title: "Badminton Doubles",
    kind: "SPORT",
    sportName: "Badminton",
    division: "MEN",
    formatLabel: "Doubles",
    registrationFee: 400,
    winnerPrize: 7000,
    runnerUpPrize: 4000,
    displayOrder: 6,
  },
  {
    slug: "table-tennis-singles-men",
    title: "Table Tennis Singles",
    kind: "SPORT",
    sportName: "Table Tennis",
    division: "MEN",
    formatLabel: "Singles",
    registrationFee: 250,
    winnerPrize: 5000,
    runnerUpPrize: 3000,
    displayOrder: 7,
  },
  {
    slug: "table-tennis-doubles-men",
    title: "Table Tennis Doubles",
    kind: "SPORT",
    sportName: "Table Tennis",
    division: "MEN",
    formatLabel: "Doubles",
    registrationFee: 400,
    winnerPrize: 7000,
    runnerUpPrize: 4000,
    displayOrder: 8,
  },
  {
    slug: "chess-open",
    title: "Chess",
    kind: "SPORT",
    sportName: "Chess",
    division: "MIXED",
    registrationFee: 200,
    winnerPrize: 3000,
    runnerUpPrize: 2000,
    secondRunnerUpPrize: 1000,
    displayOrder: 9,
  },
  {
    slug: "volleyball-women",
    title: "Volleyball",
    kind: "SPORT",
    sportName: "Volleyball",
    division: "WOMEN",
    registrationFee: 2500,
    winnerPrize: 15000,
    runnerUpPrize: 12000,
    displayOrder: 10,
  },
  {
    slug: "basketball-women",
    title: "Basketball",
    kind: "SPORT",
    sportName: "Basketball",
    division: "WOMEN",
    registrationFee: 2500,
    winnerPrize: 15000,
    runnerUpPrize: 12000,
    displayOrder: 11,
  },
  {
    slug: "badminton-singles-women",
    title: "Badminton Singles",
    kind: "SPORT",
    sportName: "Badminton",
    division: "WOMEN",
    formatLabel: "Singles",
    registrationFee: 250,
    winnerPrize: 4000,
    runnerUpPrize: 2500,
    displayOrder: 12,
  },
  {
    slug: "badminton-doubles-women",
    title: "Badminton Doubles",
    kind: "SPORT",
    sportName: "Badminton",
    division: "WOMEN",
    formatLabel: "Doubles",
    registrationFee: 400,
    winnerPrize: 5000,
    runnerUpPrize: 3000,
    displayOrder: 13,
  },
  {
    slug: "table-tennis-singles-women",
    title: "Table Tennis Singles",
    kind: "SPORT",
    sportName: "Table Tennis",
    division: "WOMEN",
    formatLabel: "Singles",
    registrationFee: 250,
    winnerPrize: 4000,
    runnerUpPrize: 2500,
    displayOrder: 14,
  },
  {
    slug: "table-tennis-doubles-women",
    title: "Table Tennis Doubles",
    kind: "SPORT",
    sportName: "Table Tennis",
    division: "WOMEN",
    formatLabel: "Doubles",
    registrationFee: 400,
    winnerPrize: 5000,
    runnerUpPrize: 3000,
    displayOrder: 15,
  },
  {
    slug: "valorant-open",
    title: "Valorant",
    kind: "ESPORT",
    sportName: "Valorant",
    division: "OPEN",
    registrationFee: 500,
    winnerPrize: 5000,
    runnerUpPrize: 3000,
    displayOrder: 16,
  },
  {
    slug: "free-fire-open",
    title: "Free Fire",
    kind: "ESPORT",
    sportName: "Free Fire",
    division: "OPEN",
    registrationFee: 400,
    winnerPrize: 7000,
    runnerUpPrize: 3000,
    displayOrder: 17,
  },
  {
    slug: "bgmi-open",
    title: "BGMI",
    kind: "ESPORT",
    sportName: "BGMI",
    division: "OPEN",
    registrationFee: 400,
    winnerPrize: 7000,
    runnerUpPrize: 3000,
    displayOrder: 18,
  },
  {
    slug: "real-cricket-open",
    title: "Real Cricket",
    kind: "ESPORT",
    sportName: "Real Cricket",
    division: "OPEN",
    registrationFee: 100,
    winnerPrize: 5000,
    runnerUpPrize: 3000,
    displayOrder: 19,
  },
];
